version: 2.1

commands:
  dagger-install:
    steps:
      - run:
          name: Install deps
          command: pip install -r ./ci/requirements-dagger.txt
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
jobs:
  dod:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run: 
          name: Set commit message
          environment:
            GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1
          command: echo $GIT_COMMIT_DESC
      - run:
          name: Install deps
          command: pip install -r ./ci/requirements-dod.txt
      - run:
          name: Run DoD validation
          command: python ./ci/dod.py
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - dagger-install
      - run:
          name: Run Dagger pipeline
          command: dagger run --progress plain python ./ci/build.py
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/project
      - dagger-install
      - run:
          name: Run Dagger pipeline
          command: dagger run --progress plain python ./ci/deploy.py
workflows:
  dagger:
    jobs:
      - dod
      - build:
          requires:
            - dod
      - deploy:
          requires:
            - build